let root = 'http://www.doutu66.com'
export const IHOME = `${root}/scdc/visit`
export const ILOGIN = `${root}/scdc/user/login`
export const IACCOUNT = `${root}/scdc/user/search`
export const IACCOUNTADD = `${root}/scdc/user/add`
export const IACCOUNTDELETE = `${root}/scdc/user/remove`
export const IBANNERGET = `${root}/scdc/banner`
export const IBANNERGETDELETE = `${root}/scdc/banner/remove`
export const IBANNERGETADD = `${root}/scdc/banner/add`
export const IMESSAGEGET = `${root}/scdc/comment/list`
export const IMESSAGEDELETE = `${root}/scdc/comment/delete`
export const IMESSAGEADD = `${root}/scdc/comment/add`
export const IDRUGLISTGET = `${root}/scdc/content/category`
export const ICATEGORYADD = `${root}/scdc/content/category`
export const IMODIFYPASSWORD = `${root}/scdc/user/modify`
// 类型
export const ICATEGORY = `${root}/scdc/content/category`
export const IWORDLISTGET = `${root}/scdc/content/list`
export const IWORDREMOVE = `${root}/scdc/content/remove`
export const IWORDSEARCH = `${root}/scdc/content/search`